---
extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - prettier
  - react
rules:
  prettier/prettier: error
